/*
Project Euler Problem 2: Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
 */


public class Main {

    public static void main(String[] args) {
        int f = 1;
        int g = 1;
        int temp;
        int answer = 0;

        while (f < 4000000){
            temp = f;
            f = f + g;
            g = temp;
            //add all the even fib numbers
            if (f % 2 == 0){
                answer = answer + f;
            }
        }

        String solution = Integer.toString(answer);
        System.out.print(solution);
    }
}
